#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main()
{
    // Define a buffer
    char buffer[100];

    // Define Palindrome Checker variable
    int Palindrome = 1; // Make it true as your base scenario

    // Request user input
    printf("Input string or integer value: ");
    fgets(buffer, sizeof(buffer), stdin);

    // Remove newline character generated by fgets
    buffer[strcspn(buffer,"\n")] = '\0';
    
    // Define length of buffer
    int length = strlen(buffer);

    // Check to see if the value is a string
    // We divide by two because we are only worried about the first
    // half of terms. If the input is of odd length value
    // it is fine because integer division in C truncates the decimal
    // meaning 5/2 = 2.
    for(int i = 0; i < length / 2; i++)
    {
        // Case where input is not a palindrone
        // We subtract on since C starts index at 0
        if(buffer[i] != buffer[length - i - 1])
        {
            Palindrome = 0;
            break;
        }
    }

    // Print true if Palindrone or false if not
    // Case 1: False
    if(Palindrome == 0)
    {
        printf("False, you input is not a Palindrome\n");
    }

    // Case 2: True
    else
    {
        printf("True, you input is a Palindrome\n");
    }

    return 0;
}